// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-caVEm9Ijdp-ptr-anxBMY6yMJ8G9WMg',
    appId: '1:630120582179:web:11ad4ad03feaaf69327596',
    messagingSenderId: '630120582179',
    projectId: 'cloud-kitchen-8c22e',
    authDomain: 'cloud-kitchen-8c22e.firebaseapp.com',
    storageBucket: 'cloud-kitchen-8c22e.appspot.com',
    measurementId: 'G-Z23XPBNX1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwc_Q1gHzn2ROsdtc8NzdQ8wDWkHTPX1A',
    appId: '1:630120582179:android:9dddd904f3117987327596',
    messagingSenderId: '630120582179',
    projectId: 'cloud-kitchen-8c22e',
    storageBucket: 'cloud-kitchen-8c22e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGuw6ELOrC-LjrGnQPynHW3PPQiMu5MGM',
    appId: '1:630120582179:ios:81ad34114ad0eeb0327596',
    messagingSenderId: '630120582179',
    projectId: 'cloud-kitchen-8c22e',
    storageBucket: 'cloud-kitchen-8c22e.appspot.com',
    iosBundleId: 'com.example.cloudkitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGuw6ELOrC-LjrGnQPynHW3PPQiMu5MGM',
    appId: '1:630120582179:ios:977f3055523fbc27327596',
    messagingSenderId: '630120582179',
    projectId: 'cloud-kitchen-8c22e',
    storageBucket: 'cloud-kitchen-8c22e.appspot.com',
    iosBundleId: 'com.example.cloudkitchen.RunnerTests',
  );
}
